# OSINT Monitor — Source Registry Seed Config
# Edit this file to add/remove conflicts and sources.
# Run `docker compose run --rm telegram-ingester python /scripts/seed_db.py` to apply.

conflicts:
  - name: "US/Israel-Iran"
    short_code: "israel-iran"
    involved_countries: ["IL", "IR", "LB", "PS", "SY", "YE", "IQ"]
    map_center_lat: 32.0
    map_center_lon: 35.0
    map_zoom_level: 5
    color_scheme:
      allies:
        countries: ["IL"]
        color: "#4CAF50"
      adversaries:
        countries: ["IR", "SY"]
        color: "#F44336"
      involved:
        countries: ["LB", "IQ", "YE", "PS"]
        color: "#FF9800"

  - name: "Russia-Ukraine"
    short_code: "russia-ukraine"
    involved_countries: ["UA", "RU", "BY"]
    map_center_lat: 49.0
    map_center_lon: 32.0
    map_zoom_level: 5
    color_scheme:
      allies:
        countries: ["UA"]
        color: "#4CAF50"
      adversaries:
        countries: ["RU", "BY"]
        color: "#F44336"

  - name: "Sudan Civil War"
    short_code: "sudan"
    involved_countries: ["SD"]
    map_center_lat: 15.5
    map_center_lon: 32.5
    map_zoom_level: 5
    color_scheme:
      involved:
        countries: ["SD"]
        color: "#FF9800"

  - name: "Taiwan Strait"
    short_code: "taiwan-china"
    involved_countries: ["TW", "CN", "JP", "PH"]
    map_center_lat: 24.0
    map_center_lon: 121.0
    map_zoom_level: 5
    color_scheme:
      allies:
        countries: ["TW"]
        color: "#4CAF50"
      adversaries:
        countries: ["CN"]
        color: "#F44336"
      involved:
        countries: ["JP", "PH"]
        color: "#FF9800"

  - name: "Korean Peninsula"
    short_code: "korean-peninsula"
    involved_countries: ["KR", "KP", "JP"]
    map_center_lat: 38.0
    map_center_lon: 127.0
    map_zoom_level: 6
    color_scheme:
      allies:
        countries: ["KR"]
        color: "#4CAF50"
      adversaries:
        countries: ["KP"]
        color: "#F44336"
      involved:
        countries: ["JP"]
        color: "#FF9800"

  - name: "US-Venezuela"
    short_code: "venezuela"
    involved_countries: ["VE", "CO", "GY", "BR"]
    map_center_lat: 7.0
    map_center_lon: -66.0
    map_zoom_level: 5
    color_scheme:
      adversaries:
        countries: ["VE"]
        color: "#F44336"
      involved:
        countries: ["CO", "GY", "BR"]
        color: "#FF9800"

  - name: "US-Greenland"
    short_code: "greenland"
    involved_countries: ["GL", "DK"]
    map_center_lat: 72.0
    map_center_lon: -40.0
    map_zoom_level: 3
    color_scheme:
      allies:
        countries: ["DK"]
        color: "#4CAF50"
      involved:
        countries: ["GL"]
        color: "#FF9800"

  - name: "South China Sea"
    short_code: "south-china-sea"
    involved_countries: ["CN", "PH", "VN", "TW", "MY"]
    map_center_lat: 12.0
    map_center_lon: 114.0
    map_zoom_level: 5
    color_scheme:
      allies:
        countries: ["PH", "VN"]
        color: "#4CAF50"
      adversaries:
        countries: ["CN"]
        color: "#F44336"
      involved:
        countries: ["MY", "TW"]
        color: "#FF9800"

  - name: "Sahel Crisis"
    short_code: "sahel"
    involved_countries: ["ML", "NE", "BF", "TD", "NG"]
    map_center_lat: 14.0
    map_center_lon: 2.0
    map_zoom_level: 5
    color_scheme:
      involved:
        countries: ["ML", "NE", "BF", "TD", "NG"]
        color: "#FF9800"

  - name: "Somalia"
    short_code: "somalia"
    involved_countries: ["SO", "ET", "KE", "DJ"]
    map_center_lat: 5.0
    map_center_lon: 46.0
    map_zoom_level: 5
    color_scheme:
      involved:
        countries: ["SO", "ET", "KE", "DJ"]
        color: "#FF9800"

  - name: "Myanmar Civil War"
    short_code: "myanmar"
    involved_countries: ["MM", "TH", "CN", "IN"]
    map_center_lat: 19.0
    map_center_lon: 96.0
    map_zoom_level: 5
    color_scheme:
      involved:
        countries: ["MM", "TH"]
        color: "#FF9800"

sources:
  telegram:
    - identifier: BellumActaNews
      display_name: "Bellum Acta News"
      reliability_tier: "medium"

    - identifier: tabzlive
      display_name: "Tabz Live"
      reliability_tier: "medium"

    - identifier: rnintel
      display_name: "RN Intel"
      reliability_tier: "medium"

    - identifier: intelslava
      display_name: "Intel Slava"
      reliability_tier: "medium"

    - identifier: GeoPWatch
      display_name: "Geopolitical Watch"
      reliability_tier: "high"

    - identifier : nothingeverhappenscorner
      display_name: "Nothing Ever Happens Corner"
      reliability_tier: "high"

  x: []
